name: CI/CD Pipeline - FastAPI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: hello-app
  DOCKER_REGISTRY: docker.io
  MANIFESTS_REPO: seu-usuario/hello-manifests
  MANIFESTS_BRANCH: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Run tests
        run: |
          python -c "from main import app; print('App imported successfully')"

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
      image_name: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{date 'YYYYMMDD'}}-,
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Output image tag
        run: |
          echo "Image tags: ${{ steps.meta.outputs.tags }}"
          echo "First tag: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}"

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFESTS_REPO }}
          ref: ${{ env.MANIFESTS_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: manifests

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get image tag from previous job
        id: get-tag
        run: |
          # Extrai a primeira tag da lista
          TAGS='${{ needs.build-and-push.outputs.image_tag }}'
          FIRST_TAG=$(echo "$TAGS" | cut -d',' -f1)
          echo "FIRST_TAG=$FIRST_TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $FIRST_TAG"

      - name: Update image tag in deployment.yaml
        run: |
          cd manifests
          NEW_IMAGE="${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.outputs.FIRST_TAG }}"
          echo "Updating image to: $NEW_IMAGE"
          sed -i "s|image:.*|image: $NEW_IMAGE|" deployment.yaml
          
          # Exibe o conteúdo atualizado para debug
          echo "Updated deployment.yaml:"
          cat deployment.yaml

      - name: Commit and push changes
        run: |
          cd manifests
          git add deployment.yaml
          git status
          git commit -m "CI: Update image to ${{ steps.get-tag.outputs.FIRST_TAG }} [skip ci]"
          git push origin ${{ env.MANIFESTS_BRANCH }}