name: CI/CD Build and Update Manifests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hello-app:latest
            ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}

      - name: Prepare SSH for manifests repo
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MANIFESTS_REPO }} # e.g. user/hello-manifests
          path: manifests
          persist-credentials: false
          ssh-strict: true

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Update manifest image tag
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}
          yq eval -i ".spec.template.spec.containers[0].image = strenv(IMAGE)" manifests/deployment.yaml
          cd manifests
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add deployment.yaml
          git commit -m "ci: update image to $IMAGE"
          git push origin main
        env:
          IMAGE: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}