name: CI/CD Pipeline - FastAPI App

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: hello-app
  MANIFESTS_REPO: git@github.com:Dasko7b/hello-manifests.git
  MANIFESTS_BRANCH: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Run tests
        run: |
          python -c "from main import app; print('App imported successfully')"

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    outputs:
      image_tag: ${{ steps.generate-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate tag
        id: generate-tag
        run: |
          TAG="${GITHUB_SHA:0:7}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Generated tag: $TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.generate-tag.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  create-pr-for-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout manifests repo via SSH
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFESTS_REPO }}
          ref: ${{ env.MANIFESTS_BRANCH }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: manifests-repo

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch for update
        run: |
          cd manifests-repo
          BRANCH_NAME="update-image-${{ needs.build-and-push.outputs.image_tag }}"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Update image tag in deployment.yaml
        run: |
          cd manifests-repo
          NEW_IMAGE="${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}"
          echo "Updating image to: $NEW_IMAGE"
          
          # Verifica se o arquivo existe
          if [ ! -f "deployment.yaml" ]; then
            echo "❌ deployment.yaml not found!"
            ls -la
            exit 1
          fi
          
          # Atualiza a tag da imagem
          sed -i "s|image:.*|image: $NEW_IMAGE|g" deployment.yaml
          
          echo "✅ Updated deployment.yaml:"
          cat deployment.yaml

      - name: Commit changes
        run: |
          cd manifests-repo
          git add deployment.yaml
          git status
          git commit -m "CI: Update image to ${{ needs.build-and-push.outputs.image_tag }}"

      - name: Push branch to remote
        run: |
          cd manifests-repo
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: manifests-repo
          branch: ${{ env.BRANCH_NAME }}
          base: ${{ env.MANIFESTS_BRANCH }}
          title: "CI: Update image to ${{ needs.build-and-push.outputs.image_tag }}"
          body: |
            Automatic PR generated by CI/CD pipeline
            
            - **New image**: `${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}`
            - **Source commit**: ${{ github.sha }}
            - **Triggered by**: ${{ github.actor }}
            
            This PR updates the Docker image tag in the deployment manifest.
          labels: "ci-cd,automated"
          delete-branch: true