name: CI/CD Pipeline (com SSH)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código da aplicação
      - name: Checkout código da aplicação
        uses: actions/checkout@v4

      # 2. Faz login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Constrói e envia a imagem Docker
      - name: Build e Push da imagem Docker
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/hello-app
          TAG=$(date +%s)
          echo "Nova tag de imagem: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      # 4. Configura a chave SSH para autenticação
      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh/
          # Escreve a chave privada do segredo para um arquivo
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # Define as permissões corretas para a chave
          chmod 600 ~/.ssh/id_rsa
          # Adiciona o host do GitHub aos hosts conhecidos para evitar prompts interativos
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # 5. Clona o repositório de manifests usando a URL SSH
      - name: Clonar repositório de manifests via SSH
        uses: actions/checkout@v4
        with:
          # ATENÇÃO: Use a URL SSH do seu repositório aqui
          repository: Dasko7b/hello-manifests
          # Clona para um diretório separado
          path: .
      # 6. Atualiza o deployment e faz o push usando a autenticação SSH já configurada
      - name: Atualizar Deployment com nova imagem
        run: |
          cd ./manifests
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.TAG }}|g" deployment.yaml
          
          # Configura o Git com as informações do bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Adiciona, commita e envia as alterações
          git add deployment.yaml
          git commit -m "CI: Atualizando imagem para a tag ${{ env.TAG }}"
          
          # O Git usará automaticamente a chave SSH configurada no passo 4
          git push